var poem_detail = { id: '2_1',
  audioUrl: 'http://www.allamaiqbal.com/works/poetry/ur/bal/audio/01-01.mp3',
  heading:
  [ { lang: 'ur', text: 'ميري نوائے شوق سے شور حريم ذات ميں' },
    { lang: 'en',
      text: 'A blaze is raging near His Throne, By my strains that burn like flames' } ],
  description:
  [ { lang: 'en',
    text: 'Note 1: The first five poems, inspired by Divine Love, are addressed to God. Outwardly it seems as if the poet is talking about himself, but actually he is singing Hymns in praise of God. This Ghazal excels the succeeding Ghazals in sublimity of thought, uniqueness of execution, style, figures of speech and its rapturous nature.\\n\\nThe poet owns his own non-existence and is conscious that he exists only because of God’s Creative Attribute. He is grateful to God for having blessed him with the boundless Passion of Love for Him, which lends wings to his poesy and he can find access to the precincts of the Absolute Being. He is a true lover of God and is not contented, like others, to realise His Essence through His Attributes. Though he is fully aware that Houris and Angels, being creatures of light, are aery, yet he can catch them in the lassoo of his imagination. His sharp and piercing glances can ruffle the moulds in which He manifests Himself, but sometimes the doubts - and conflicts that smoulder in his breast make him miss the mark. God by creating man, who is the image of God on earth, has divulged the mystery that lay hid in the womb of Nature.\\n\\nNote 2: Mr. Naeem Siddiqui did not translate this ode. So, the translation of this ode has been taken from Gabriel’s Wing by Syed Akbar Ali Shah.' } ],
  sher:
  [ { id: '2_1_1',
    meta: false,
    sherContent:
    [ { lang: 'ur',
      text: 'ميري نوائے شوق سے شور حريم ذات ميں\\nغلغلہ ہائے الاماں بت کدئہ صفات ميں' },
      { lang: 'ro',
        text: 'Meri Nawa’ay Shauq Se Shor Hareem-e-Zaat Mein\\nGhalghala Ha’ay Al-Aman But Kada’ay Sifaat Mein' },
      { lang: 'en',
        text: 'A blaze is raging near His Throne, By my strains that burn like flames\\nThe cries of "Mercy !" rise aloft, From the Temple of His Names.',
        notes:
        [ { phrase: 'blaze', occurrence: '1', meaning: 'Conflagration' },
          { phrase: 'His Throne',
            meaning: 'the precincts of the Absolute Being or Harirn-i-Zat, the original word in the text' },
          { phrase: 'strains', meaning: 'songs' },
          { phrase: 'aloft', meaning: 'on high' },
          { phrase: 'Temple of His Names',
            meaning: 'The Temple of His attributes' } ] } ] },
    { id: '2_1_2',
      sherContent:
      [ { lang: 'ur',
        text: 'حور و فرشتہ ہيں اسير ميرے تخيلات ميں\\nميري نگاہ سے خلل تيري تجليات ميں' },
        { lang: 'ro',
          text: 'Hoor-o-Farishta Hain Aseer Mere Takhiyulat Mein\\nMeri Nigah Se Khalal Teri Tajaliat Mein' },
        { lang: 'en',
          text: 'Houris and angels, all alike, My soaring thought can keep in hold:\\nThe moulds $6 in which Thou dost reveal, Get ruffled $7 by my glances bold.',
          notes:
          [ { phrase: 'moulds',
            meaning: 'shapes i.e., the different aspects in which God displays Himself.' },
            { phrase: 'ruffled', meaning: 'disturbed' } ] } ] },
    { id: '2_1_3',
      sherContent:
      [ { lang: 'ur',
        text: 'گرچہ ہے ميري جستجو دير و حرم کي نقش بند\\nميري فغاں سے رستخيز کعبہ و سومنات ميں' },
        { lang: 'ro',
          text: 'Garche Hai Meri Justujoo Dair-e-Haram Ki Naqsh Band\\nMeri Faghan Se Rustkhaiz Kaaba-O-Somanat Mein' },
        { lang: 'en',
          text: 'In my search and quest for Thee, Cloisters $8 and Kirks$9 I did design,\\nBut my groans and woeful wails, Can shake the founds $10 of Fane $11 and Shrine $12 .',
          notes:
          [ { phrase: 'Cloisters',
            meaning: 'a place of religious retirement, a sanctuary' },
            { phrase: 'Kirks', meaning: 'Scotch equivalent for church' },
            { phrase: 'founds', meaning: 'foundations' },
            { phrase: 'Fane', meaning: 'temple' },
            { phrase: 'Shrine', meaning: 'sanctuary' } ] } ] },
    { id: '2_1_4',
      sherContent:
      [ { lang: 'ur',
        text: 'گاہ مري نگاہ تيز چير گئي دل وجود\\nگاہ الجھ کے رہ گئي ميرے توہمات ميں' },
        { lang: 'ro',
          text: 'Gah Meri Nigah-e-Taiz Cheer Gyi Dil-e-Wujood\\nGah Uljah Ke Reh Gyi Meri Touwahamaat Mein' },
        { lang: 'en',
          text: 'There were times when my vision sharp, Pierced the heart and core of Life:\\nTime again, fell short of mark $13 , By mine inner doubts and strife.',
          notes: [ { phrase: 'mark', meaning: 'target' } ] } ] },
    { id: '2_1_5',
      sherContent:
      [ { lang: 'ur',
        text: 'تو نے يہ کيا غضب کيا، مجھ کو بھي فاش کر ديا\\n!ميں ہي تو اک راز تھا سينہء کائنات ميں' },
        { lang: 'ro',
          text: 'Tu Ne Ye Kya Ghazab Kiya, Mujh Ko Bhi Fash Kar Diya\\nMain Hi Tou Aik Raaz Tha Sina’ay Kainat Mein !' },
        { lang: 'en',
          text: 'I was the only secret veil’d, In Nature’s Womb in Latent $15 form:\\nWhen I was brought to light for show, What wondrous act Thou didst perform!',
          notes:
          [ { phrase: 'Womb',
            meaning: 'Uterus, the organ in which the young of mammals are developed and kept till birth, the word in the poem is Sina-i-Kainat' },
            { phrase: 'Latent', meaning: 'hidden' } ] } ] } ] };